import './globals.css'
import { Bebas_Neue } from 'next/font/google'
import Header from './header/header-main/page'


const bebasNeue = Bebas_Neue({
  subsets: ['latin'],
  weight: ['400']
})

export const metadata = {
  title: 'Display All Dept New',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bebasNeue.className}>
        <main>
          <div className="flex flex-col h-[1200px] w-[1600px] p-[30px] bg-[#9DA5EE] gap-[25px]">
            <Header />
            <div className="col w-full h-[925px] flex gap-[30px]">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  )
}
