import './globals.css'
import { Bebas_Neue } from 'next/font/google'


const bebasNeue = Bebas_Neue({
  subsets: ['latin'],
  weight: ['400']
})

export const metadata = {
  title: 'Display All Dept New',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bebasNeue.className}>{children}</body>
    </html>
  )
}
